/**
 * A pure, portable in-game calendar date. No dependency on JS `Date`, `Intl`,
 * or any host clock — the whole module is arithmetic on plain numbers, which
 * keeps it trivial to port to the eventual Unity/C# build.
 *
 * IMPORTANT: these are SIMULATION dates generated by systems/calendar/, not
 * sourced real-world fixture dates. Nothing in this module or its callers may
 * present a GameDate as an official/announced date.
 */
export interface GameDate {
  year: number;
  month: number; // 1..12
  day: number; // 1..31
}

function isLeapYear(year: number): boolean {
  return (year % 4 === 0 && year % 100 !== 0) || year % 400 === 0;
}

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

export function daysInMonth(year: number, month: number): number {
  if (month === 2 && isLeapYear(year)) return 29;
  return DAYS_IN_MONTH[month - 1] as number;
}

/**
 * Converts to a Julian Day Number using the standard Fliegel & Van Flandern
 * algorithm for the proleptic Gregorian calendar. This gives correct,
 * closed-form (non-iterative) date arithmetic across month/year/leap-year
 * boundaries without depending on any host Date implementation.
 */
export function toDayNumber(date: GameDate): number {
  const a = Math.floor((14 - date.month) / 12);
  const y = date.year + 4800 - a;
  const m = date.month + 12 * a - 3;
  return (
    date.day +
    Math.floor((153 * m + 2) / 5) +
    365 * y +
    Math.floor(y / 4) -
    Math.floor(y / 100) +
    Math.floor(y / 400) -
    32045
  );
}

export function fromDayNumber(jdn: number): GameDate {
  const a = jdn + 32044;
  const b = Math.floor((4 * a + 3) / 146097);
  const c = a - Math.floor((146097 * b) / 4);
  const d = Math.floor((4 * c + 3) / 1461);
  const e = c - Math.floor((1461 * d) / 4);
  const m = Math.floor((5 * e + 2) / 153);
  const day = e - Math.floor((153 * m + 2) / 5) + 1;
  const month = m + 3 - 12 * Math.floor(m / 10);
  const year = 100 * b + d - 4800 + Math.floor(m / 10);
  return { year, month, day };
}

export function addDays(date: GameDate, days: number): GameDate {
  return fromDayNumber(toDayNumber(date) + days);
}

/** Negative if a < b, 0 if equal, positive if a > b. */
export function compareDates(a: GameDate, b: GameDate): number {
  return toDayNumber(a) - toDayNumber(b);
}

export function isBefore(a: GameDate, b: GameDate): boolean {
  return compareDates(a, b) < 0;
}

export function isSameDate(a: GameDate, b: GameDate): boolean {
  return compareDates(a, b) === 0;
}

const THAI_MONTH_ABBR = [
  'ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.',
  'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.',
];

/**
 * Simple pure formatter (no Intl), mirroring the precedent of formatBaht in
 * core/money.ts — a display-string helper that lives with its type so the
 * UI never re-implements date arithmetic or labelling itself.
 */
export function formatGameDate(date: GameDate): string {
  return `${date.day} ${THAI_MONTH_ABBR[date.month - 1]} ${date.year}`;
}
