import type { NationalityCategory, PlayerVerification, Position } from '../core/player';

/**
 * ============================================================================
 * RESEARCHED REAL SQUADS
 * ============================================================================
 * Every squad here comes from a research document supplied and explicitly
 * approved for import by the project owner. Each document's own governance
 * rules are honoured in code, not just by hand:
 *
 *  - RESEARCHED != APPROVED FOR IMPORT. Nothing auto-imports; this file is
 *    only reached because the owner performed the Approval step by hand.
 *  - Source and verification status are preserved PER PLAYER and PER SQUAD.
 *  - Conflicts the documents raised are NEVER resolved here. Both sides are
 *    kept and the entry is marked CONFLICTED with the document's reason.
 *  - Nothing unevidenced is invented. A field the document did not establish
 *    is simply absent, and players.seed.ts fills it with a clearly-labelled
 *    simulated value so the club stays playable.
 *
 * `importStatus` distinguishes how far a squad got in that pipeline:
 *   TIER1     - the document treated the list as current-squad evidence from
 *               a Tier 1 source (the club's own official Team page).
 *   PROVISIONAL - the document marked itself PARTIAL/PROVISIONAL and
 *               "Import Status: NOT APPROVED", pending Tier 1 verification.
 *
 * Ability, age and wage are NOT in this file. Those are simulated game values
 * generated by players.seed.ts, so no fabricated statistic is ever attached
 * to a real person as if it were fact.
 */
export type SquadImportStatus = 'TIER1' | 'PROVISIONAL';

export interface ResearchedPlayer {
  /** Absent when the source did not establish a shirt number. */
  squadNumber?: number;
  name: string;
  /** Absent when the source left the position unverified. */
  position?: Position;
  /** Verbatim from the source, including dual nationalities. Absent when the
   *  source gave no country (e.g. only the word "Foreign", or "VERIFY"). */
  nationality?: string;
  /**
   * Confederation grouping of the FIRST-listed nationality. Geographic fact,
   * derived from the source's own listing — not a league registration ruling.
   * 'unknown' where the source did not name a country.
   */
  nationalityCategory: NationalityCategory;
  /**
   * What the source said about foreign status, when it said anything. A
   * document can establish that a player IS foreign (e.g. BG Pathum's list
   * says only "Foreign") without naming a country — that is `isForeign: true`
   * with `nationalityCategory: 'unknown'`. Absent means the source never
   * established it at all, and no claim is made either way.
   */
  isForeign?: boolean;
  verification: PlayerVerification;
  /** Set when the source document flagged this entry for further checking. */
  note?: string;
}

export interface ResearchedSquad {
  clubId: string;
  /** Guards against the seed order changing under us. */
  expectedClubName: string;
  source: string;
  importStatus: SquadImportStatus;
  /** Why the squad carries the status it does, in the document's own terms. */
  statusNote: string;
  /** Squad-level problems the source document raised and did not resolve. */
  documentedConflicts: string[];
  /** Entries the source explicitly excluded from the current squad. */
  notImported: string[];
  players: ResearchedPlayer[];
}


const BURIRAM_UNITED: ResearchedSquad = {
  clubId: 'T1-01',
  expectedClubName: 'บุรีรัมย์ ยูไนเต็ด',
  source: 'เว็บไซต์ทางการ Buriram United — หน้า Team (research pass 2026/27)',
  importStatus: 'TIER1',
  statusNote: 'เอกสารต้นทางระบุสถานะ RESEARCHED / CURRENT-SQUAD EVIDENCE จากหน้า Team ทางการของสโมสร',
  documentedConflicts: [],
  notImported: [
    'Uroš Radaković',
    'Nathan Pele',
    'Mark Navarro',
    'Jakraphan Praisuwan',
    'Vukan Savićević',
    'Darlan Mendes',
    'Sebastián Moyano',
    'Alexandru Tudorie',
    'Stefan Schimmer',
  ],
  players: [
    { squadNumber: 13, name: 'Neil Etheridge', position: 'GK', nationality: 'ฟิลิปปินส์/อังกฤษ', nationalityCategory: 'asean', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 34, name: 'ฉัตรชัย บุตรพรม', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 29, name: 'กรพัฒน์ นารีจันทร์', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 2, name: 'ศศลักษณ์ ไหประโคน', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 3, name: 'พรรษา เหมวิบูลย์', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 5, name: 'ธีราทร บุญมาทัน', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 6, name: 'Curtis Good', position: 'DF', nationality: 'ออสเตรเลีย', nationalityCategory: 'asian', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 14, name: 'Sandy Walsh', position: 'DF', nationality: 'อินโดนีเซีย/เบลเยียม', nationalityCategory: 'asean', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 15, name: 'นฤบดินทร์ วีรวัฒโนดม', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 22, name: 'Go Myung-Seok', position: 'DF', nationality: 'เกาหลีใต้', nationalityCategory: 'asian', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 30, name: 'Filip Stojković', position: 'DF', nationality: 'มอนเตเนโกร/เซอร์เบีย', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 40, name: 'Eduardo Mancha', position: 'DF', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 75, name: 'ชินภัทร์ ลีเอาะ', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 8, name: 'รัตนากร ใหม่คามิ', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 11, name: 'ปฐมพล เจริญรัตนาภิรมย์', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 16, name: 'Kenny Dougall', position: 'MF', nationality: 'ออสเตรเลีย', nationalityCategory: 'asian', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 23, name: 'Goran Čaušić', position: 'MF', nationality: 'เซอร์เบีย', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 26, name: 'Toku Emmanuel', position: 'MF', nationality: 'กานา', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 27, name: 'พิธิวัตต์ สุขจิตธรรมกุล', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 32, name: 'Robert Žulj', position: 'MF', nationality: 'ออสเตรีย', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 33, name: 'ธนกฤต โชติเมืองปัก', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 44, name: 'Peter Žulj', position: 'MF', nationality: 'ออสเตรีย', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 54, name: 'ณฐกร รัตนสุวรรณ', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 19, name: 'Kingsley Schindler', position: 'MF', nationality: 'กานา/เยอรมนี', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 7, name: 'Guilherme Bissoli', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 9, name: 'ศุภชัย ใจเด็ด', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 10, name: 'ศุภณัฏฐ์ เหมือนตา', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'RESEARCHED' },
    { squadNumber: 17, name: 'Ilhan Fandi', position: 'FW', nationality: 'สิงคโปร์', nationalityCategory: 'asean', isForeign: true, verification: 'CONFLICTED', note: 'เอกสารต้นทางระบุให้ตรวจสอบข้อขัดแย้งของรายการนี้เป็นพิเศษ' },
    { squadNumber: 28, name: 'Rubén Sánchez', position: 'FW', nationality: 'สเปน', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
    { squadNumber: 77, name: 'Casper Jørgensen', position: 'FW', nationality: 'เดนมาร์ก', nationalityCategory: 'other', isForeign: true, verification: 'RESEARCHED' },
  ],
};

const BG_PATHUM_UNITED: ResearchedSquad = {
  clubId: 'T1-02',
  expectedClubName: 'บีจี ปทุม ยูไนเต็ด',
  source: 'ประกาศรายชื่อ 29 นักเตะ ฤดูกาล 2026/27 เลกแรก (รายงานข่าว 12 ก.ค. 2026) — cross-check Transfermarkt',
  importStatus: 'PROVISIONAL',
  statusNote: 'เอกสารต้นทางระบุ Research Status: FOUND / PROVISIONAL และ Import Status: NOT APPROVED',
  documentedConflicts: [
    'ประกาศต้นทางใช้เบอร์ 30 ซ้ำกัน 2 คน (อิทธิมนต์ ทิพเนตร และ ไรอัน เอ็ดเวิร์ดส์)',
    'นับผู้เล่นที่ระบุว่า Foreign ได้ 12 คน แต่เอกสารระบุโควตาต่างชาติในประกาศ 11 คน',
    'สัญชาติต่างชาติระบุเพียงคำว่า Foreign ไม่มีชื่อประเทศ จึงแยกหมวดอาเซียน/เอเชียไม่ได้',
    'Transfermarkt แสดงผู้เล่นและสัญญาบางรายต่างจากรายชื่อประกาศ',
  ],
  notImported: [],
  players: [
    { squadNumber: 2, name: 'ชานนท์ ทำมา', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 4, name: 'ลีออน เจมส์', position: 'MF', nationality: 'ไทย/อังกฤษ', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 5, name: 'กฤษดา กาแมน', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 6, name: 'สารัช อยู่เย็น', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'เอกสารต้นทางระบุ CONFLICT / VERIFY และห้าม resolve เอง' },
    { squadNumber: 7, name: 'รานีล ซานตานา', position: 'FW', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 8, name: 'อัครพงศ์ พุ่มวิเศษ', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 9, name: 'สุรชาติ สารีพิมพ์', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 10, name: 'ลูคัส อันเดอร์เซ่น', position: 'MF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 11, name: 'พาตริก กุสตาฟส์สัน', position: 'FW', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 13, name: 'อิสระพงษ์ แววดี', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 14, name: 'โทโมยูกิ โดอิ', position: 'FW', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 15, name: 'ชนภัช บัวพันธ์', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 16, name: 'ทาคาฮิโระ ยานากิ', position: 'DF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 18, name: 'ชนาธิป สรงกระสินธ์', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 19, name: 'แอชลีย์ คอฟฟีย์', position: 'MF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 21, name: 'พัสคัล แฟร์คัมพ์', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 24, name: 'สหรัฐ ปองสุวรรณ', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 25, name: 'ปวีร์ ตัณฑะเตมีย์', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 26, name: 'อ็องโตนี เบลมงต์', position: 'MF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 27, name: 'พงศ์รวิช จันทวงษ์', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 28, name: 'สรานนท์ อนุอินทร์', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 30, name: 'อิทธิมนต์ ทิพเนตร', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'ประกาศต้นทางใช้เบอร์ 30 ซ้ำกับผู้เล่นอีกราย — เอกสารระบุให้ตรวจทะเบียนก่อนใช้เป็นเบอร์ที่ไม่ซ้ำ' },
    { squadNumber: 30, name: 'ไรอัน เอ็ดเวิร์ดส์', position: 'MF', nationalityCategory: 'unknown', isForeign: true, verification: 'CONFLICTED', note: 'ประกาศต้นทางใช้เบอร์ 30 ซ้ำกับผู้เล่นอีกราย — เอกสารระบุให้ตรวจทะเบียนก่อนใช้เป็นเบอร์ที่ไม่ซ้ำ' },
    { squadNumber: 37, name: 'ฟาบิโอ คอฟมันน์', position: 'FW', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 44, name: 'มาร์โก นิโคลิช', position: 'DF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 45, name: 'เจา มักโน่', position: 'FW', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 48, name: 'วาริส ชูทอง', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 49, name: 'นราวิชญ์ อินทเจริญ', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 50, name: 'เอดิน ออสมาโนวิช', position: 'DF', nationalityCategory: 'unknown', isForeign: true, verification: 'PROVISIONAL' },
  ],
};

const PT_PRACHUAP: ResearchedSquad = {
  clubId: 'T1-07',
  expectedClubName: 'พีที ประจวบ เอฟซี',
  source: 'FotMob / AiScore / WorldFootball / SalarySport snapshot 2026/27 (แหล่ง cross-check ไม่ใช่ Tier 1)',
  importStatus: 'PROVISIONAL',
  statusNote: 'เอกสารต้นทางระบุ Research Status: PARTIAL / PROVISIONAL และ Import Status: NOT APPROVED',
  documentedConflicts: [
    'จำนวนผู้เล่นไม่ตรงกันระหว่างแหล่ง: FotMob 33 คน, AiScore 34 คน, ตารางในเอกสาร 38 รายการ',
    'Tauã ปรากฏสองแถวในเอกสาร (MID/FW ไม่มีเบอร์ และ FW เบอร์ 10) เอกสารตีธง DUPLICATE POSITION DATA',
    'ผู้เล่นหลายรายไม่มีหลักฐานหมายเลขเสื้อ (ช่อง -) จึงคงเป็น UNKNOWN ไม่เดา',
    'ผู้เล่นหลายรายมีสถานะ CONTRACT / MEMBERSHIP VERIFY',
  ],
  notImported: [],
  players: [
    { squadNumber: 1, name: 'Rattanai Songsangchan', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 18, name: 'Soponwit Rakyart', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 39, name: 'Wattanachai Srathongjan', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 99, name: 'Abdulfarus Sama-aeh', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 2, name: 'Oussama Thiangkham', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 3, name: 'Bernardo Vilar Estevão Jeronimo', position: 'DF', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 4, name: 'Adrian Ugelvik', position: 'DF', nationality: 'ฟิลิปปินส์', nationalityCategory: 'asean', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 5, name: 'Airton Tirabassi', position: 'DF', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { squadNumber: 15, name: 'Jesper Nyholm', position: 'DF', nationality: 'ฟิลิปปินส์', nationalityCategory: 'asean', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 21, name: 'Apisit Sorada', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 66, name: 'Wanchat Choosong', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 74, name: 'Phon-Ek Jensen Maneekorn', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 88, name: 'Jirapan Phasukihan', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 19, name: 'Prommin Pinkaew', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Aymen Thiangkham', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Pittawat Jeenthai', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Nick Taylor', position: 'DF', nationality: 'กัมพูชา', nationalityCategory: 'asean', isForeign: true, verification: 'PROVISIONAL' },
    { name: 'Nattapong Hamontree', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Rei Tachikawa', position: 'MF', nationality: 'ญี่ปุ่น', nationalityCategory: 'asian', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 70, name: 'Prasid Jantum', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { name: 'Saharat Kanyarot', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Kannarin Thawornsak', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Jittiphat Wasungnoen', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { name: 'Wuttikai Sritong', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { name: 'Tailson', position: 'MF', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 10, name: 'Tauã', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'CONFLICTED', note: 'เอกสารต้นทางแสดง Tauã สองแถว (MID/FW ไม่มีเบอร์ และ FW เบอร์ 10) และตีธง DUPLICATE POSITION DATA — รวมเป็นคนเดียวโดยยังไม่สรุปตำแหน่ง' },
    { name: 'Koki Tsukagawa', position: 'MF', nationality: 'ญี่ปุ่น', nationalityCategory: 'asian', isForeign: true, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { squadNumber: 40, name: 'Chaowat Veerachart', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { name: 'Andros Townsend', position: 'FW', nationality: 'อังกฤษ', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { name: 'Lee Jeong-Hyeop', position: 'FW', nationality: 'เกาหลีใต้', nationalityCategory: 'asian', isForeign: true, verification: 'PROVISIONAL' },
    { name: 'Édgar Méndez', position: 'FW', nationality: 'สเปน', nationalityCategory: 'other', isForeign: true, verification: 'CONFLICTED', note: 'CONTRACT / MEMBERSHIP VERIFY ตามเอกสารต้นทาง' },
    { name: 'Michel', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 28, name: 'Soffan Sanhorn', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 41, name: 'Phanthamit Praphanth', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 47, name: 'Chitsanuphong Phimpsang', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 48, name: 'Jehhanafee Mamah', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 91, name: 'Chrigor Moraes', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 13, name: 'Yodsakorn Burapha', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
  ],
};

const TRUE_BANGKOK_UNITED: ResearchedSquad = {
  clubId: 'T1-04',
  expectedClubName: 'แบงค็อก ยูไนเต็ด',
  source: 'Transfermarkt / Football Team News (แหล่ง cross-check ไม่ใช่ Tier 1)',
  importStatus: 'PROVISIONAL',
  statusNote: 'เอกสารต้นทางระบุ Research Status: FOUND / PROVISIONAL และ Import Status: NOT APPROVED',
  documentedConflicts: [
    'คอลัมน์ # ในเอกสารเป็นลำดับแถว 1-28 ไม่ใช่หมายเลขเสื้อ และเอกสารระบุเองว่าหมายเลขเสื้อยังไม่ยืนยันจาก Tier 1 จึงไม่นำเข้าเลย',
    'เอกสารไม่มีคอลัมน์สัญชาติ จึงระบุสัญชาติและสิทธิ์โควตาต่างชาติไม่ได้ทั้งทีม',
    'ผู้เล่นทุกรายมีสถานะ Current Membership: VERIFY / UNVERIFIED',
    'Boontawee Thepwong ปรากฏในชุดข้อมูลปัตตานี เอฟซี ด้วย',
  ],
  notImported: [],
  players: [
    { name: 'Patiwat Khammai', position: 'GK', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Phuwadol Pholsongkram', position: 'GK', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Chinnapong Raksri', position: 'GK', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Supanut Sudathip', position: 'GK', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Philipe Maia', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Kritsada Nontharat', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Suphan Thongsong', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Everton', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Wichan Inaram', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Anaphat Nakngam', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Wanchai Jarunongkran', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Ki-je Lee', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Bhumchanok Kamkla', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Surachai Booncharee', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'James Beresford', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Boontawee Thepwong', position: 'DF', nationalityCategory: 'unknown', verification: 'CONFLICTED', note: 'ชื่อเดียวกันปรากฏในชุดข้อมูลปัตตานี เอฟซี (#22 MF) ด้วย — ต้องตรวจสังกัดปัจจุบัน' },
    { name: 'Nontapat Ploymee', position: 'DF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Weerathep Pomphun', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'John-Patrick Strauß', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Natcha Promsomboon', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Wisarut Imura', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Picha Autra', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Thitiphan Puangchan', position: 'MF', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Rivaldinho', position: 'FW', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Guntapon Keereeleang', position: 'FW', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Teerasil Dangda', position: 'FW', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Nopparat Promiem', position: 'FW', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
    { name: 'Thanawat Deelert', position: 'FW', nationalityCategory: 'unknown', verification: 'PROVISIONAL' },
  ],
};

const PATTANI_FC: ResearchedSquad = {
  clubId: 'T1-14',
  expectedClubName: 'ปัตตานี เอฟซี',
  source: 'เว็บไซต์ทางการ Pattani FC — หน้า squad (pattanifc.co/squad) — cross-check Transfermarkt/Siamsport',
  importStatus: 'PROVISIONAL',
  statusNote: 'เอกสารต้นทางระบุสถานะ PARTIAL / NOT APPROVED',
  documentedConflicts: [
    'เว็บไซต์สโมสรแสดง 20 รายชื่อ แต่ Transfermarkt snapshot 26/27 แสดง 19 คน และรายชื่อ/หมายเลขไม่ตรงกัน',
    'ชื่อผู้เล่นเป็นชื่อแสดงบนเว็บสโมสร (เช่น B. Chaiyawat, M. Silva) ไม่ใช่ชื่อเต็ม',
    'มีรายงานผู้เล่นเข้าใหม่หลายรายที่ยังไม่ปรากฏในหน้า squad เช่น Ignacio Abeledo, Maicon Douglas',
    'Boontawee ปรากฏในชุดข้อมูล True Bangkok United ด้วย',
  ],
  notImported: [],
  players: [
    { squadNumber: 1, name: 'Ninurudin', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 13, name: 'Damyan', position: 'GK', nationality: 'มองโกเลีย', nationalityCategory: 'asian', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 46, name: 'Phosaman', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 2, name: 'Ekkachai', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 5, name: 'Nuttawut', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 11, name: 'Janepoop', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 24, name: 'B. Chaiyawat', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 26, name: 'M. Silva', position: 'DF', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 36, name: 'Kittipong', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 40, name: 'Kirati', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 4, name: 'Nattayot', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 7, name: 'Adhthep', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 19, name: 'Itttipon', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 22, name: 'Boontawee', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'CONFLICTED', note: 'ชื่อ Boontawee Thepwong ปรากฏในชุดข้อมูล True Bangkok United ด้วย — ต้องตรวจสังกัดปัจจุบัน' },
    { squadNumber: 30, name: 'Lassamano', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 32, name: 'Anuwa', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 64, name: 'Thirapak', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 61, name: 'Arion', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 90, name: 'Imron', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 96, name: 'Carlos Neto', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
  ],
};

const SISAKET_UNITED: ResearchedSquad = {
  clubId: 'T1-15',
  expectedClubName: 'ศรีสะเกษ ยูไนเต็ด',
  source: 'ประกาศเปิดตัวทีม 28 รายชื่อเรียงตามหมายเลขเสื้อ (Siamsport 31 ส.ค. 2026) — cross-check Transfermarkt/BeSoccer',
  importStatus: 'PROVISIONAL',
  statusNote: 'เอกสารต้นทางระบุ Research Status: PARTIAL / PROVISIONAL และ Import Status: NOT APPROVED',
  documentedConflicts: [
    'ตำแหน่งของผู้เล่น 23 จาก 28 รายเป็น VERIFY ในเอกสาร คือยังไม่ทราบตำแหน่ง',
    'สัญชาติหลายรายเป็น VERIFY หรือมีเครื่องหมาย ? (เช่น ไทย/สวิตเซอร์แลนด์?, บราซิล?)',
    'ชื่อเต็ม/สัญชาติ/ตำแหน่งของ Victor Golas, Alex Mermoz, Jefinho, Patrick Valverde Lopez และ Isaac Honey ต้องตรวจเพื่อสร้าง Stable Player ID',
    'แหล่งประกาศเป็นสื่อ (Siamsport) ไม่ใช่ประกาศทางการของสโมสร/ผู้จัดการแข่งขัน',
  ],
  notImported: [],
  players: [
    { squadNumber: 1, name: 'Victor Golas', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารต้นทางเป็น VERIFY — ยังไม่ยืนยัน' },
    { squadNumber: 2, name: 'Denis Darbellay', nationality: 'ไทย/สวิตเซอร์แลนด์?', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารมีเครื่องหมาย ? — ยังไม่ยืนยัน' },
    { squadNumber: 3, name: 'Guilherme Baldo Borech', nationality: 'บราซิล?', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารมีเครื่องหมาย ? — ยังไม่ยืนยัน' },
    { squadNumber: 5, name: 'Pakornkiat Kaena', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 7, name: 'Alex Mermoz', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารต้นทางเป็น VERIFY — ยังไม่ยืนยัน' },
    { squadNumber: 8, name: 'Hikaru Matsui', nationality: 'ญี่ปุ่น', nationalityCategory: 'asian', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 9, name: 'Jefinho', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารต้นทางเป็น VERIFY — ยังไม่ยืนยัน' },
    { squadNumber: 10, name: 'Deyvison Fernandes', nationality: 'บราซิล', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 11, name: 'Phattharapong Phengchaem', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 17, name: 'Wongsakorn Saenruecha', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 19, name: 'Kittipong Wongma', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 20, name: 'Patrick Valverde Lopez', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารต้นทางเป็น VERIFY — ยังไม่ยืนยัน' },
    { squadNumber: 22, name: 'Pongsakron Hanrattana', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 23, name: 'Narongrit Kamnet', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 27, name: 'Piyawat Intarapim', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL', note: 'ตำแหน่งในเอกสารระบุ GK? — ยังไม่ยืนยัน' },
    { squadNumber: 35, name: 'Isaac Honey', nationalityCategory: 'unknown', verification: 'PROVISIONAL', note: 'สัญชาติในเอกสารต้นทางเป็น VERIFY — ยังไม่ยืนยัน' },
    { squadNumber: 37, name: 'Suphaphon Sutthisak', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 39, name: 'Anusak Jaiphet', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL', note: 'ตำแหน่งในเอกสารระบุ DEF? — ยังไม่ยืนยัน' },
    { squadNumber: 44, name: 'Natthasan Pakkarano', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 45, name: 'Chutikom Klinchampasri', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL', note: 'ตำแหน่งในเอกสารระบุ DEF? — ยังไม่ยืนยัน' },
    { squadNumber: 55, name: 'Krittidet Nuntawong', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 67, name: 'Athit Buangam', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 70, name: 'Sorasak Khampanja', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL', note: 'ตำแหน่งในเอกสารระบุ GK? — ยังไม่ยืนยัน' },
    { squadNumber: 88, name: 'Sakkarawit Nimma', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 92, name: 'Thanison Paibulkijcharoen', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 93, name: 'Mahamadou Doucouré', nationality: 'มาลี', nationalityCategory: 'other', isForeign: true, verification: 'PROVISIONAL' },
    { squadNumber: 97, name: 'Suttichai Pongson', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL' },
    { squadNumber: 99, name: 'Sittichok Kannoo', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', isForeign: false, verification: 'PROVISIONAL', note: 'ตำแหน่งในเอกสารระบุ FW? — ยังไม่ยืนยัน' },
  ],
};


export const RESEARCHED_SQUADS: Record<string, ResearchedSquad> = {
  [BURIRAM_UNITED.clubId]: BURIRAM_UNITED,
  [BG_PATHUM_UNITED.clubId]: BG_PATHUM_UNITED,
  [TRUE_BANGKOK_UNITED.clubId]: TRUE_BANGKOK_UNITED,
  [PT_PRACHUAP.clubId]: PT_PRACHUAP,
  [PATTANI_FC.clubId]: PATTANI_FC,
  [SISAKET_UNITED.clubId]: SISAKET_UNITED,
};

export function researchedSquadFor(clubId: string): ResearchedSquad | null {
  return RESEARCHED_SQUADS[clubId] ?? null;
}
