import type { NationalityCategory, PlayerVerification, Position } from '../core/player';

/**
 * ============================================================================
 * RESEARCHED REAL SQUADS
 * ============================================================================
 * Source document: "BURIRAM UNITED — CURRENT SQUAD RESEARCH, ฤดูกาล 2026/27",
 * supplied and explicitly approved for import by the project owner.
 *
 * The source document's own governance rules are honoured here:
 *
 *  - RESEARCHED != APPROVED FOR IMPORT. This file is only reached because the
 *    project owner performed the Approval step by hand. Nothing auto-imports.
 *  - Source and verification status are preserved PER PLAYER.
 *  - Nothing not evidenced by the document is invented here. There are no
 *    DOB, preferred-foot or contract fields, because the document has none.
 *  - Entries the document listed as "seen in news / pre-season but NOT to be
 *    counted as Current Squad" are kept in NOT_IMPORTED below and are
 *    deliberately never loaded into runtime.
 *
 * Ability, age and wage are NOT in this file. Those are simulated game values
 * generated by players.seed.ts and flagged `attributesSimulated: true`, so no
 * fabricated statistic is ever attached to a real person as if it were fact.
 */
export interface ResearchedPlayer {
  squadNumber: number;
  name: string;
  position: Position;
  /** Verbatim from the source, including dual nationalities. */
  nationality: string;
  /**
   * Confederation grouping of the FIRST-listed nationality. Geographic fact,
   * derived from the source's own listing — not a league registration ruling.
   */
  nationalityCategory: NationalityCategory;
  verification: PlayerVerification;
  /** Set when the source document flagged this entry for further checking. */
  note?: string;
}

export interface ResearchedSquad {
  clubId: string;
  /** Guards against the seed order changing under us. */
  expectedClubName: string;
  source: string;
  /** Entries the source explicitly excluded from the current squad. */
  notImported: string[];
  players: ResearchedPlayer[];
}

const BURIRAM_UNITED: ResearchedSquad = {
  clubId: 'T1-01',
  expectedClubName: 'บุรีรัมย์ ยูไนเต็ด',
  source: 'เว็บไซต์ทางการ Buriram United — หน้า Team (research pass 2026/27)',
  notImported: [
    'Uroš Radaković',
    'Nathan Pele',
    'Mark Navarro',
    'Jakraphan Praisuwan',
    'Vukan Savićević',
    'Darlan Mendes',
    'Sebastián Moyano',
    'Alexandru Tudorie',
    'Stefan Schimmer',
  ],
  players: [
    // ผู้รักษาประตู
    { squadNumber: 13, name: 'Neil Etheridge', position: 'GK', nationality: 'ฟิลิปปินส์/อังกฤษ', nationalityCategory: 'asean', verification: 'RESEARCHED' },
    { squadNumber: 34, name: 'ฉัตรชัย บุตรพรม', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 29, name: 'กรพัฒน์ นารีจันทร์', position: 'GK', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },

    // กองหลัง
    { squadNumber: 2, name: 'ศศลักษณ์ ไหประโคน', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 3, name: 'พรรษา เหมวิบูลย์', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 5, name: 'ธีราทร บุญมาทัน', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 6, name: 'Curtis Good', position: 'DF', nationality: 'ออสเตรเลีย', nationalityCategory: 'asian', verification: 'RESEARCHED' },
    { squadNumber: 14, name: 'Sandy Walsh', position: 'DF', nationality: 'อินโดนีเซีย/เบลเยียม', nationalityCategory: 'asean', verification: 'RESEARCHED' },
    { squadNumber: 15, name: 'นฤบดินทร์ วีรวัฒโนดม', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 22, name: 'Go Myung-Seok', position: 'DF', nationality: 'เกาหลีใต้', nationalityCategory: 'asian', verification: 'RESEARCHED' },
    { squadNumber: 30, name: 'Filip Stojković', position: 'DF', nationality: 'มอนเตเนโกร/เซอร์เบีย', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 40, name: 'Eduardo Mancha', position: 'DF', nationality: 'บราซิล', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 75, name: 'ชินภัทร์ ลีเอาะ', position: 'DF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },

    // กองกลาง
    { squadNumber: 8, name: 'รัตนากร ใหม่คามิ', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 11, name: 'ปฐมพล เจริญรัตนาภิรมย์', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 16, name: 'Kenny Dougall', position: 'MF', nationality: 'ออสเตรเลีย', nationalityCategory: 'asian', verification: 'RESEARCHED' },
    { squadNumber: 23, name: 'Goran Čaušić', position: 'MF', nationality: 'เซอร์เบีย', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 26, name: 'Toku Emmanuel', position: 'MF', nationality: 'กานา', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 27, name: 'พิธิวัตต์ สุขจิตธรรมกุล', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 32, name: 'Robert Žulj', position: 'MF', nationality: 'ออสเตรีย', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 33, name: 'ธนกฤต โชติเมืองปัก', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 44, name: 'Peter Žulj', position: 'MF', nationality: 'ออสเตรีย', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 54, name: 'ณฐกร รัตนสุวรรณ', position: 'MF', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 19, name: 'Kingsley Schindler', position: 'MF', nationality: 'กานา/เยอรมนี', nationalityCategory: 'other', verification: 'RESEARCHED' },

    // กองหน้า
    { squadNumber: 7, name: 'Guilherme Bissoli', position: 'FW', nationality: 'บราซิล', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 9, name: 'ศุภชัย ใจเด็ด', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    { squadNumber: 10, name: 'ศุภณัฏฐ์ เหมือนตา', position: 'FW', nationality: 'ไทย', nationalityCategory: 'thai', verification: 'RESEARCHED' },
    {
      squadNumber: 17,
      name: 'Ilhan Fandi',
      position: 'FW',
      nationality: 'สิงคโปร์',
      nationalityCategory: 'asean',
      // Source document §5 singles this entry out for conflict checking.
      verification: 'CONFLICTED',
      note: 'เอกสารต้นทางระบุให้ตรวจสอบข้อขัดแย้งของรายการนี้เป็นพิเศษ',
    },
    { squadNumber: 28, name: 'Rubén Sánchez', position: 'FW', nationality: 'สเปน', nationalityCategory: 'other', verification: 'RESEARCHED' },
    { squadNumber: 77, name: 'Casper Jørgensen', position: 'FW', nationality: 'เดนมาร์ก', nationalityCategory: 'other', verification: 'RESEARCHED' },
  ],
};

export const RESEARCHED_SQUADS: Record<string, ResearchedSquad> = {
  [BURIRAM_UNITED.clubId]: BURIRAM_UNITED,
};

export function researchedSquadFor(clubId: string): ResearchedSquad | null {
  return RESEARCHED_SQUADS[clubId] ?? null;
}
